export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVED_FROM_CART = "REMOVED_FROM_CART";
export const EMPTY_FROM_CART = "EMPTY_FROM_CART";
export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_SEARCH = "PRODUCT_SEARCH";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";